Project/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('accounts/',include('accounts.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"

urlpatterns = [
    path('login/', views.login_view,name="login"),
    path('signup/', views.signup_view,name="signup"),
    path('profile/', views.profile,name="profile"),
    path('logout/', views.logout_view,name="logout"),
    path('qrcode/', views.qrcode_view,name="qrcode"),
    path('created/', views.created,name="created"),
]

core/urls.py
from django.urls import path
from core import views
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [
    path('', TemplateView.as_view(template_name="core/index.html"),name="index"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User,AbstractUser


class MyUser(AbstractUser):
   username = models.CharField(max_length=150,unique=False,blank=True)	
   email = models.EmailField(unique = True)
   USERNAME_FIELD = 'email'
   REQUIRED_FIELDS = ['username']

   def __str__(self):
   	return self.email


class UserAuth(models.Model):
	secret_key = models.CharField(max_length = 255)
	has_two = models.BooleanField(default = False)
	user = models.OneToOneField(MyUser,on_delete = models.CASCADE)

	def __str__(self):
		return f"{self.user.email} : Auth"

core/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from accounts.models import MyUser
from django.contrib.auth.forms import UserCreationForm

from django import forms

class LoginForm(forms.Form):
	email = forms.EmailField()
	password = forms.CharField(widget=forms.PasswordInput())
	otp = forms.CharField(max_length = 20,required = False)

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = MyUser
        fields = ("email",)

accounts/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponse

import qrcode
import qrcode.image.svg
import pyotp

from accounts.forms import LoginForm,CustomUserCreationForm
from accounts.models import UserAuth


def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request,email = email,password = password)
            if user:
                if user.userauth.has_two:
                    otp = form.cleaned_data['otp']
                    if not pyotp.TOTP(user.userauth.secret_key).verify(otp):
                        messages.error(request, 'Your Two Factor is ON')
                        messages.error(request, 'Please Enter Valid TOTP')
                        return render(request,"accounts/login.html")
                login(request,user)
                return redirect("accounts:profile")
        messages.error(request, 'Invalid Email/Password.')
    return render(request,"accounts/login.html")


def signup_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            user = form.save()
            UserAuth.objects.create(secret_key = pyotp.random_base32(),user = user)
            send_mail('Account Created Successfully','Your Account Has Been Created.','lukasgarden05@gmail.com',[email])
            return redirect('accounts:created')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


@login_required
def qrcode_view(request):
    url = pyotp.totp.TOTP(request.user.userauth.secret_key).provisioning_uri(name=request.user.email, issuer_name='Secure App')
    img = qrcode.make(url, image_factory=qrcode.image.svg.SvgImage)
    response = HttpResponse(content_type='image/svg+xml')
    img.save(response)
    return response


@login_required
def profile(request):
    auth = request.user.userauth
    if request.method == 'POST':
        auth.has_two = True if request.POST.get("has_two") else False
        auth.save()
        return redirect("accounts:profile")
    return render(request,"accounts/profile.html",{'has_two':auth.has_two})


def logout_view(request):
    logout(request)
    return redirect("accounts:login")


def created(request):
    return render(request,"accounts/created.html")

core/views.py
from django.shortcuts import render

accounts/templates/accounts/created.html
  
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
<title>created</title>
{% endblock %}

{% block content %}
    <div class="container mx-auto p-2 max-w-2xl">
      <h1 class="text-center text-3xl font-bold text-gray-900 my-24 mx-auto px-5 py-10">
        Your Account Has Been Created and confirmation email has been sent. Please Login to continue.
      </h1>
    </div>
{% endblock %}

accounts/templates/accounts/login.html
  
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block content %}

      <div class="max-w-md mx-auto my-24 bg-white px-5 py-10 rounded shadow-xl">
        <div class="text-center mb-3">
      <h2 class="text-center text-3xl font-bold text-gray-900 mb-5">
        Login
      </h2>
		{% if messages %}
	        {% for message in messages %}
				<div class="text-red-700 px-6 py-2 border-0 rounded relative mb-2 bg-red-100 text-center">
				  <span class="inline-block align-middle mr-8">
				    {{ message|escape }}
				  </span>
				</div>
	        {% endfor %}
		{% endif %}

        </div>

        <form method="post">
        	{% csrf_token %}
          <div class="mt-5">
            <label for="username">Email</label>
            <input
              type="email"
              id="username"
              name="email"
              required="true"
              class="block w-full p-2 border rounded border-gray-500"
            />
          </div>
          <div class="mt-5">
            <label for="password">Password</label>
            <input
              type="password"
              id="password"
              name="password"
              required="true"
              class="block w-full p-2 border rounded border-gray-500"
            />
          </div>
          <div class="mt-5">
            <label for="password">Totp (If Two Factor Enabled)</label>
            <input
              type="text"
              id="password"
              name="otp"
              class="block w-full p-2 border rounded border-gray-500"
            />
          </div>
          <div class="mt-10">
            <input
              type="submit"
              value="Login"
              class="py-3 rounded text-white text-center w-full bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            />
          </div>
        </form>
      </div>

{% endblock %}

accounts/templates/accounts/profile.html
  
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block content %}

      <div class="max-w-md mx-auto my-24 bg-white px-5 py-10 rounded shadow-xl">
        <div class="text-center mb-3">
      <h2 class="text-center text-3xl font-bold text-gray-900 mb-5">
        Profile
      </h2>
      <span>{{ user.email }}</span>
        </div>

        <form method="post">
        	{% csrf_token %}
		{% if has_two %}
          <div class="mt-5 text-center">
            <img class="mx-auto" src="{% url 'accounts:qrcode' %}"></img>
          </div>
		{% endif %}
          <div class="mt-5 text-center">
            <label class="inline-flex items-center mt-3">
                <input type="checkbox" name="has_two" class="form-checkbox h-5 w-5 text-gray-600" {% if has_two %}checked{% endif %}><span class="ml-2 text-gray-700">Two Factor Authentication</span>
            </label>
          </div>
          <div class="mt-10">
            <input
              type="submit"
              value="Update"
              class="py-3 rounded text-white text-center w-full bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            />
          </div>

        </form>
      </div>
{% endblock %}

accounts/templates/accounts/signup.html
  
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
<title>Signup</title>
{% endblock %}

{% block content %}

      <div class="max-w-md mx-auto my-24 bg-white px-5 py-10 rounded shadow-xl">
        <div class="text-center mb-3">
      <h2 class="text-center text-3xl font-bold text-gray-900 mb-5">
        Register
      </h2>
		{% if form.errors %}
		    {% for field in form %}
		        {% for error in field.errors %}
					<div class="text-red-700 px-6 py-2 border-0 rounded relative mb-2 bg-red-100 text-center">
					  <span class="inline-block align-middle mr-8">
					    {{ error|escape }}
					  </span>
					</div>
		        {% endfor %}
		    {% endfor %}
		{% endif %}

        </div>

        <form method="post">
        	{% csrf_token %}
          <div class="mt-5">
            <label for="username">Email</label>
            <input
              type="email"
              id="username"
              name="email"
              required="true"
              class="block w-full p-2 border rounded border-gray-500"
            />
          </div>
          <div class="mt-5">
            <label for="password">Password</label>
            <input
              type="password"
              id="password"
              name="password1"
              required="true"
              class="block w-full p-2 border rounded border-gray-500"
            />
          </div>
          <div class="mt-5">
            <label for="password">Confirm Password</label>
            <input
              type="password"
              id="password"
              name="password2"
              required="true"
              class="block w-full p-2 border rounded border-gray-500"
            />
          </div>
          <div class="mt-10">
            <input
              type="submit"
              value="Signup"
              class="py-3 rounded text-white text-center w-full bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
            />
          </div>
        </form>
      </div>

{% endblock %}

core/templates/core/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block head %}{% endblock %}
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'core/tailwind.css' %}"> -->
	<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="antialiased bg-gray-200 text-gray-900 font-sans">
<nav class="bg-gray-800">
  <div class="max-w-6xl mx-auto px-4">
    <div class="flex justify-between">

      <div class="flex space-x-4">
        <!-- logo -->
        <div>
          <a href="{% url 'core:index' %}" class="flex items-center py-5 px-1 text-gray-700 hover:text-gray-900"> <img class="block h-8 w-auto" src="https://tailwindui.com/img/logos/workflow-mark-indigo-500.svg" alt="Workflow">
          </a>
        </div>

      </div>

      <div class="hidden md:flex items-center space-x-5">
            <a href="{% url 'core:index' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium" aria-current="page">Home</a>
			{% if user.is_authenticated %}
            <a href="{% url 'accounts:profile' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Profile</a>

            <a href="{% url 'accounts:logout' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Logout</a> 
			{% else %}
            <a href="{% url 'accounts:login' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Login</a>

            <a href="{% url 'accounts:signup' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Signup</a> 
			{% endif %}     
        </div>

      <!-- mobile button goes here -->
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
        </button>
      </div>

    </div>
  </div>

  <!-- mobile menu -->
  <div class="mobile-menu hidden md:hidden">
    <a href="{% url 'core:index' %}" class="block py-3 px-4 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Home</a>
	{% if user.is_authenticated %}
    <a href="{% url 'accounts:profile' %}" class="block py-3 px-4 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Profile</a>

    <a href="{% url 'accounts:logout' %}" class="block py-3 px-4 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Logout</a> 
	{% else %}
    <a href="{% url 'accounts:login' %}" class="block py-3 px-4 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Login</a>

    <a href="{% url 'accounts:signup' %}" class="block py-3 px-4 text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Signup</a> 
	{% endif %} 

  </div>
</nav>
{% block content %}
{% endblock %}

{% block javascript %}
{% endblock %}
<script type="text/javascript">

const btn = document.querySelector("button.mobile-menu-button");
const menu = document.querySelector(".mobile-menu");

btn.addEventListener("click", () => {
  menu.classList.toggle("hidden");
});

</script>
</body>
</html>

core/templates/core/index.html
  
{% extends 'core/base.html' %}
{% load static %}

{% block head %}
<title>Home</title>
{% endblock %}

{% block content %}

    <div class="container mx-auto p-2">
      <h1 class="text-center text-4xl font-bold text-gray-900 my-24 mx-auto px-5 py-10">
        Welcome To This Test Site
      </h1>
    </div>

{% endblock %}